name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    services:
      rabbitmq:
        image: rabbitmq:latest
        ports:
          - 5672:5672
        # needed because the rabbitmq container does not provide a healthcheck
        options: --health-cmd "rabbitmqctl node_health_check" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies and optional extras
      run: |
        sudo apt-get install libsnappy-dev
        python -m pip install --upgrade pip
        pip install -r requirements.dev.txt
        pip install -r requirements.txt
        pip install -r requirements.extras.txt
    - name: Cache pip dependencies
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        # Check for a cache hit for the corresponding dev requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.dev.txt') }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements.extras.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Generate test support files
      run: |
        make certs
        make generate
    - name: Run code style checker
      run: |
        make check-style
    - name: Run types checker
      run: |
        make check-types
    - name: Run tests and collect code coverage
      run: |
        make check-coverage
    - name: Install package
      run: |
        pip install .
    - name: Run code linter
      # The lint rule also checks examples code which expects the package
      # to be installed.
      run: |
        make check-lint
    - name: Generate docs
      run: |
        make docs
    - name: Generate package
      run: |
        make dist
